=== lefinek/bsi-projekty/fiveth/invoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xs:element name="faktura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="numer_faktury" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="miejsce_wystawienia" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="data_wystawienia" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="termin_platnosci" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="forma_platnosci" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="data_wykonania" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="sprzedawca" type="kontrahentType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="nabywca" type="kontrahentType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="konto" type="kontoType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="uslugi" type="uslugiType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="uwagi" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="wystawiajacy" type="xs:string" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="kontrahentType">
    <xs:sequence>
      <xs:element name="nazwa" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="adres" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="NIP" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="kontoType">
    <xs:sequence>
      <xs:element name="nazwa_banku" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="numer_konta" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  

  <xs:complexType name="uslugiType">
    <xs:sequence>
      <xs:element name="usluga" type="uslugaType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  

  <xs:complexType name="uslugaType">
    <xs:sequence>
      <xs:element name="nazwa" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="ilosc" type="xs:integer" minOccurs="1" maxOccurs="1"/>
      <xs:element name="cena_jednostkowa" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
      <xs:element name="stawka_VAT" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="wartosc" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  
</xs:schema>

=== lefinek/bsi-projekty/fiveth/invoice.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="invoice.xsl"?>
<faktura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="invoice.xsd">
  <numer_faktury>
    2137/11/2025
  </numer_faktury>
  <data_wystawienia>
    17.11.2025
  </data_wystawienia>
  <miejsce_wystawienia>
    Warszawa
  </miejsce_wystawienia>
  <termin_platnosci>
    01.12.2025
  </termin_platnosci>
  <forma_platnosci>
    Gotówka
  </forma_platnosci>
  <data_wykonania>
    17.11.2025
  </data_wykonania>
  <uwagi>
    Miłego dnia!
  </uwagi>
  <wystawiajacy>
    Jakub Strzelczak
  </wystawiajacy>
  <sprzedawca>
    <nazwa>
      Sprzedawca Sp. z o.o.
    </nazwa>
    <adres>
      ul. Ulica 10, 00-001 Warszawa
    </adres>
    <NIP>
      123-456-32-18
    </NIP>
  </sprzedawca>
  <nabywca>
    <nazwa>
      Nabywca Sp. z o.o.
    </nazwa>
    <adres>
      ul. Inna Ulica 20, 00-002 Warszawa
    </adres>
    <NIP>
      987-654-32-18
    </NIP>
  </nabywca>
  <konto>
    <nazwa_banku>
      Bank
    </nazwa_banku>
    <numer_konta>
    12 3456 7890 1234 5678 9012 3456
  </numer_konta>
  </konto>
  <uslugi>
    <usluga>
      <nazwa>
        Wykonanie projektu BSI
      </nazwa>
      <ilosc>
        1
      </ilosc>
      <cena_jednostkowa>
        5000.00
      </cena_jednostkowa>
      <stawka_VAT>
        23%
      </stawka_VAT>
      <wartosc>
        6150.00
      </wartosc>
    </usluga>
    <usluga>
      <nazwa>
        Promocja strony internetowej
      </nazwa>
      <ilosc>
        1
      </ilosc>
      <cena_jednostkowa>
        2000.00
      </cena_jednostkowa>
      <stawka_VAT>
        23%
      </stawka_VAT>
      <wartosc>
        2460.00
      </wartosc>
    </usluga>
    <usluga>
      <nazwa>
        Hostowanie strony internetowej
      </nazwa>
      <ilosc>
        1
      </ilosc>
      <cena_jednostkowa>
        1000.00
      </cena_jednostkowa>
      <stawka_VAT>
        23%
      </stawka_VAT>
      <wartosc>
        1230.00
      </wartosc>
    </usluga>
    <usluga>
      <nazwa>
        Analiza SEO
      </nazwa>
      <ilosc>
        5
      </ilosc>
      <cena_jednostkowa>
        500.00
      </cena_jednostkowa>
      <stawka_VAT>
        8%
      </stawka_VAT>
      <wartosc>
        2700.00
      </wartosc>
    </usluga>
  </uslugi>
</faktura>
